### ISSUE TITLE
Probleme with using

### ISSUE THREAD

**Issue by Lyhtael** [PSK1103/VillagerNerfer#1]
Hi i recently added your plugins to my server, i realy like how it work but i got issue with it

Some npc doesnt take their job or doesnt lost job when you break job block but not all npc
Some npc doesnt level up or reset their trade but not all npc too
I got a player which could have a full shulker of book without blocking the trade

I have this error which repeats in a loop 

[11:00:53] [Server thread/WARN]: [VillagerNerfer] Task #15 for VillagerNerfer v1.7.0 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R2/entity/CraftVillager
	at me.PSK1103.VillagerNerfer.utils.VillagerStorage.professionTask(VillagerStorage.java:134) ~[VillagerNerfer.jar:?]
	at me.PSK1103.VillagerNerfer.utils.VillagerStorage$NerfedTask.run(VillagerStorage.java:103) ~[VillagerNerfer.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1492) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-125]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R2.entity.CraftVillager
	... 10 more

I think it will be good to have a nerfed nametag only mode but it's clearly not the priority

Ty for your work dude it realy cool

**Comment by PSK1103** [comment]
Hi, this version of the plugin is only limited to 1.18.2. I am planning to update it for 1.19-1.19.2 but I can't get on with it due to real life commitments. Keeping this issue open till I update it

**Comment by PSK1103** [comment]
The nerfed nametag method already exists. You can define specific values in your config.yml

**Comment by JamesDAdams** [comment]
the nametag method doesn't work in 1.19.2

**Comment by PSK1103** [comment]
The plugin has been updated for 1.19-1.19.2. [v1.8.1](https://github.com/PSK1103/VillagerNerfer/releases/tag/v1.8.1) also adds proper nametag based nerfing.
